### ISSUE TITLE
Inconsistent namespacing

### ISSUE THREAD

**Issue by Y-Less** [ad3154/Isobus-plus-plus#197]
**Describe the bug**
`CANHardwareInterface` and `SocketCANInterface` are not in the `isobus::` namespace.  I don't know what others aren't.  Is there a reason?  I know they're both part of the hardware abstraction layer, but maybe a more nested namespace like `isobus::hw::` would be more appropriate than not having them in at all.

**Comment by ad3154** [comment]
Originally the idea was to have the hardware interface be completely separate and optional for the library, and it still kind of is, so I was hesitant to put it in the same namespace. These days though it's pretty well entangled with the library and makes using it a lot easier, so we might be better off namespacing it within the isobus namespace. There's no real reason for it to be in the global namespace, that much is for sure. I would be OK with changing it's namespace, especially now before we "release" the library as "Stable".
