### ISSUE TITLE
Stuck at the isobus::NAME myNAME(0);

### ISSUE THREAD

**Issue by rahibd** [ad3154/Isobus-plus-plus#202]
Hi, I am trying to test ISOBUS-Plus-Plus with an **RPi4 and CAN hut**.
my ISOBUS hello world worked just fine. but when I just included "isobus::NAME myNAME(0);" and try to compile with "cmake --build build" got 2 errors as below. I was working for the last week on this issue, couldn't solve it.
.......................................................................
[64%] Linking CXX executable isobus_hello_world
/usr/bin/ld: ISO11783-CAN-Stack/isobus/libIsobus.a(can_NAME.cpp.o): in function _sub_I_00100_0':
/home/pi/Repository/Test/IS011783-CAN-Stack/isobus/src/can_NAME.cpp:159: undefined reference to
/usr/bin/ld: ISO11783-CAN-Stack/isobus/libIsobus.a(can_NAME.cpp.o): in function sub_D_00100_1':
/home/pi/Repository/Test/ISO11783-CAN-Stack/isobus/src/can_NAME.cpp:159: undefined reference to
_gcov_init'
/usr/bin/ld: ISO11783-CAN-Stack/isobus/libIsobus.a(can_NAME.cpp.o):(.data+0x28): undefined reference to gcov_merge_add
/usr/bin/ld: IS011783-CAN-Stack/isobus/libIsobus.a(can_stack_logger.cpp.o): in function sub_I_00100_0':
gcov_exit'
/home/pi/Repository/Test/IS011783-CAN-Stack/isobus/src/can_stack_logger.cpp:90: undefined reference to
/usr/bin/ld: IS011783-CAN-Stack/isobus/libIsobus.a(can_stack_logger.cpp.o): in function _sub_D_00100_1":
/home/pi/Repository/Test/IS011783-CAN-Stack/isobus/src/can_stack_logger.cpp:90: undefined reference to /usr/bin/ld: IS011783-CAN-Stack/isobus/libIsobus.a(can_stack_logger.cpp.o):(.data+0x2c): undefined reference to gcov_merge_add' gcov_exit'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/isobus_hello_world.dir/build.make:107: isobus_hello_world] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:270: CMakeFiles/isobus_hello_world.dir/all] Error 2 gmake: [Makefile:171: all] Error 2 ***
pi@raspberrypi:~/Repository/Test S
................................................................................

**Environment (please complete the following information):**
 - OS: Raspbian

**Comment by ad3154** [comment]
This seems like it's trying to build the unit tests, but without `gcovr`, so here are some options that might work:

- Build without testing by reconfiguring like this `cmake -S . -B build -DBUILD_TESTING=OFF` then `cmake --build build`

OR

- Install gcovr for the unit test target `pip install gcovr` assuming you have python and pip installed.
