### ISSUE TITLE
Using pre-generated binary DDOP format in TC client

### ISSUE THREAD

**Issue by GwnDaan** [ad3154/Isobus-plus-plus#227]
**Is your feature request related to a problem? Please describe.**
Hi, I've noticed that the TC object pool (DDOP) is generated at every boot. For applications running on microcontrollers, this takes a few seconds due to the lack of processing power. Especially with larger pools I image the boot times being too long for great user-experience.

**Describe the solution you'd like**
The ability to load in pre-generated binary object pools for the TC client. Possibly by overloading the current constructor?

**Comment by ad3154** [comment]
Yeah, I imagined this might be an issue. I agree with your proposal that we could allow creation of a TC with a binary DDOP as an overload.

**Comment by GwnDaan** [comment]
> For applications running on microcontrollers, this takes a few seconds due to the lack of processing power

Nevermind, the generation of the DDOP is not the cause of this. It's the "Startup delay complete" that I missed. I wonder why a startup delay is needed? Nevertheless I feel like the binary DDOP option is still a valuable feature for supporting other DDOP generators.
